name: Test mulfile

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install
      # - name: Format check with black
      #   run: |
      #     source $VENV
      #     make format-check
      # - name: Typecheck with mypy
      #   run: |
      #    source $VENV
      #    make typecheck
      - name: Test with pytest
        run: make test
